---
title: "Core PCA Analysis Functions"
author: "Wayne Monical"
date: "8/26/2021"
output: html_document
---






Library Load
```{r}
library(readr)
library(tidyverse)
library(scatterplot3d)
library(kernlab)
```


```{r}
# boolean.vector is logical as to whether the ith of n data points should be included in the analysis

begin.object <- function(boolean.vector, y.data, x.set){
  list(y.data = y.data[,boolean.vector], x.set = x.set[boolean.vector,])
}
```

```{r}
conduct.linear.pca <- function(list.object){
  
  # checks
  if(prod(names(list.object) != c("y.data", "x.set"))){
    stop("incorrect list.object. Use begin.object function")
  }
  
  
  linear.pca <- prcomp(t(list.object$y.data))
  
  c(list.object, linear.pca = list(linear.pca))
  
  
}



```

```{r}
conduct.regression2 <- function(list.object, pcas = 1:3){
  
  # lm needs a formula
  regression.formula <- (formula.function(list.object))[[1]]
  
    
  num.list <- create.numlist(pcas)  
    
  lpca.regressions <- lapply(num.list, FUN = function(y){apply.regression(y.set = list.object$linear.pca$x[,y],
                                                                          x.set = list.object$x.set,
                                                                          formula = regression.formula
                                                                          )})
  return(c(list.object, lpca.regressions = list(lpca.regressions)))
  
}



apply.regression <- function(y.set, x.set, formula){
  design.matrix <- data.frame(y.set = y.set, x.set)
  lm(formula = formula, data = design.matrix)
  }



create.numlist <- function(integer.vector){
  names(integer.vector) <-  integer.vector
  as.list(integer.vector)
}



# conduct.regression depends on formula.function
formula.function <- function(list.object){
  cell.type.include <- length(unique(list.object$x.set$Cell.Type)) > 1
  treatment.type.include <- length(unique(list.object$x.set$trtmnt.type)) > 1
  
  possible.formulas[cell.type.include  + treatment.type.include + 1]
}



# formula.function depends on this constant
possible.formulas <- c(y.set ~ trtmnt.amnt, y.set ~ trtmnt.type + trtmnt.amnt, y.set ~ Cell.Type + trtmnt.type + trtmnt.amnt)

```


