---
title: "all.boolean.PCA"
author: "Wayne Monical"
date: "5/4/2021"
output: html_document
---


requires all of pca.freshstart5.Rmd. Pipeline is taken from PCAplots.Rmd


Pipeline
```{r}
# change these
analysis <- all.obj.reg2$all.boolean
principle.components.used <- create.numlist(1:3)


# let these do the work
observations <- analysis$y.data

principle.comp.matrix <- analysis$linear.pca$rotation[,unlist(principle.components.used)]

fitted.in.pca <- lapply(names(principle.components.used), FUN = function(a){analysis$lpca.regressions[[a]]})


names(fitted.in.pca) <- principle.components.used




#### Predicted Data
####
fitted.in.pca.matrix <- sapply(fitted.in.pca, FUN = function(b){b$fitted.values})

fitted.percents <- principle.comp.matrix %*% t(fitted.in.pca.matrix)

# adding mutation columns!
fitted.percents <- mutate(as.data.frame(fitted.percents), mutation = all.reads$`By mutation(s)`)

# unstacking
fitted.percents.unstack <- pivot_longer(data = fitted.percents, cols = -mutation, names_to = "sample", values_to = "percent")


fitted.percents.unstack <- mutate(fitted.percents.unstack, obs.or.predict = "Prediction")




####  Observation Data
####
observations <- mutate(observations, mutation = all.reads$`By mutation(s)`)

observed.percents.unstack <- pivot_longer(data = observations, cols = -mutation, names_to = "sample", values_to = "percent")

observed.percents.unstack <- mutate(observed.percents.unstack, obs.or.predict = "Observation")




#### Row Binding
####


final.percents <- rbind(fitted.percents.unstack, observed.percents.unstack)

# adding experiment information
rownames(experiment.information) <- experiment.information$entire
final.percents <- cbind(final.percents, experiment.information[ final.percents$sample,])


final.percents



```

Plotting

```{r}
all.percent.sum <- apply(all.reads[,all.boolean], 1, sum)
mutation.subsample <- all.reads$`By mutation(s)`[order(all.percent.sum, decreasing = TRUE)][1:10]

subsample <- filter(final.percents, (trtmnt.type == "Ola" | trtmnt.type == "mock") & mutation %in% mutation.subsample & !percent < 0.1)

ggplot(data = subsample, aes(x = trtmnt.amnt, y = percent, color = mutation)) +
  geom_point(data = subset(subsample, obs.or.predict == "Observation"), aes(x = trtmnt.amnt, y = percent, color = mutation, shape = obs.or.predict))  +
  geom_line(data = subset(subsample, obs.or.predict == "Prediction"), aes(x = trtmnt.amnt, y = percent, color = mutation, shape = obs.or.predict))  +
  theme(legend.position = "none")+
  labs(title = "Principle Component Analysis on Olaparib Haploid Experiments", x = "Olaparib Concentration", y = "Allele Percentage") 




all.percent.sum <- apply(all.reads[,all.hap], 1, sum)
mutation.subsample <- all.reads$`By mutation(s)`[order(all.percent.sum, decreasing = TRUE)][c(1,3, 4)]

subsample <- filter(final.percents, (trtmnt.type == "Ola" | trtmnt.type == "mock") & mutation %in% mutation.subsample & !percent < 1)

ggplot(data = subsample, aes(x = trtmnt.amnt, y = percent, color = mutation)) +
  geom_point(data = subset(subsample, obs.or.predict == "Observation"), aes(x = trtmnt.amnt, y = percent, color = mutation))  +
  geom_line(data = subset(subsample, obs.or.predict == "Prediction"), aes(x = trtmnt.amnt, y = percent, color = mutation, shape = obs.or.predict))  +
  labs(title = "Regressing Three Mutations", x = "Olaparib Concentration", y = "Allele Percentage") 




all.percent.sum <- apply(all.reads[,all.hap], 1, sum)
mutation.subsample <- all.reads$`By mutation(s)`[order(all.percent.sum, decreasing = TRUE)][1:10]

subsample <- filter(final.percents, trtmnt.type == "Nira" & mutation %in% mutation.subsample & !percent < 0.01)

ggplot(data = subsample, aes(x = trtmnt.amnt, y = percent, color = mutation)) +
  geom_point(data = subset(subsample, obs.or.predict == "Observation"), aes(x = trtmnt.amnt, y = percent, color = mutation, shape = obs.or.predict))  +
  geom_line(data = subset(subsample, obs.or.predict == "Prediction"), aes(x = trtmnt.amnt, y = percent, color = mutation, shape = obs.or.predict))  +
  theme(legend.position = "none") 



all.percent.sum <- apply(all.reads[,all.hap], 1, sum)
mutation.subsample <- all.reads$`By mutation(s)`[order(all.percent.sum, decreasing = TRUE)][1]

subsample <- filter(final.percents, trtmnt.type == "Nira" & mutation %in% mutation.subsample & !percent < 0.01)

ggplot(data = subsample, aes(x = trtmnt.amnt, y = percent, color = mutation)) +
  geom_point(data = subset(subsample, obs.or.predict == "Observation"), aes(x = trtmnt.amnt, y = percent, color = mutation))  +
  geom_line(data = subset(subsample, obs.or.predict == "Prediction"), aes(x = trtmnt.amnt, y = percent, color = mutation, shape = obs.or.predict))  
  




all.percent.sum <- apply(all.reads[,all.dip], 1, sum)
mutation.subsample <- all.reads$`By mutation(s)`[order(all.percent.sum, decreasing = TRUE)][1:10]

subsample <- filter(final.percents, trtmnt.type == "Ola" & mutation %in% mutation.subsample & !percent < 0.01)

ggplot(data = subsample, aes(x = trtmnt.amnt, y = percent, color = mutation)) +
  geom_point(data = subset(subsample, obs.or.predict == "Observation"), aes(x = trtmnt.amnt, y = percent, color = mutation, shape = obs.or.predict))  +
  geom_line(data = subset(subsample, obs.or.predict == "Prediction"), aes(x = trtmnt.amnt, y = percent, color = mutation, shape = obs.or.predict))  +
  theme(legend.position = "none")


```


```{r}
filter(subsample, obs.or.predict == "Observation")
```




```{r}
top.mutations <- as.list(all.reads$`By mutation(s)`[1:50])
names(top.mutations) <- all.reads$`By mutation(s)`[1:50]


first.50.regressions <- lapply(top.mutations, function(x){
  
  temp.df <- filter(final.percents, obs.or.predict == "Observation" , mutation == x)
  
  if(x %in% all.reads$`By mutation(s)`[1:10]){
    filter(temp.df, percent > 1)
  }
  lm(percent ~ Cell.Type + trtmnt.amnt + trtmnt.type, data = temp.df)
  
})

first.50.coef <- lapply(first.50.regressions, FUN = function(x){x$coefficients[3]})

plot(unlist(first.50.coef))
```



```{r} 
plot(all.obj.reg2$all.boolean$linear.pca$rotation[1:50, 3])


el.2nd.val <- all.obj.reg2$all.boolean$linear.pca$rotation[1:50,3] * all.obj.reg2$all.boolean$lpca.regressions$`3`$coefficients[5]
text.index <- rep(NULL, 50)
text.index[abs(el.2nd.val) > 0.1 ] <- all.reads$`By mutation(s)`[1:50] [abs(el.2nd.val) > 0.1]

plot(1:50, el.2nd.val, main = "First 50 Elements of The Second Principle Component", xlab = "Index", ylab = "Percent Change Coresp. to 1-Unit Increase in Dose")  + text(1:50, el.2nd.val, text.index, cex = 0.8, pos = 4)

# comparted to a regression
plot(1:50, el.2nd.val,  xlab = "Index", ylab = "Percent Change Coresp. to 1-Unit Increase in Dose", main = "PCA Slopes Versus Individually Fit Slopes")  + points(1:50, unlist(first.50.coef), col = "red")




plot(1:50, el.2nd.val, main = "Slope Term of Treatment Amount Assigned to Each Mutation", xlab = "Index", ylab = "Percent Change Coresp. to 1-Unit Increase in Dose")  + text(1:50, el.2nd.val, text.index, cex = 0.8, pos = 4)


















plot(all.obj.reg2$all.hap$linear.pca$rotation[1:50,3])
plot(all.obj.reg2$all.hap$linear.pca$rotation[1:50,4])

hist(all.obj.lreg2$all.boolean$linear.pca$x[,1])



hist(all.obj.lreg2$all.hap$linear.pca$x[,1])
hist(all.obj.lreg2$all.hap$linear.pca$x[,2])
hist(all.obj.lreg2$all.hap$linear.pca$x[,3])


plot(all.obj.reg2$lpca.regression$residuals)
```


